FROM golang

#Add real values
ENV MAIL_GUN_DOMAIN=MAIL_GUN_DOMAIN
ENV MAIL_GUN_API_KEY=MAIL_GUN_API_KEY
ENV SENDGRID_API_KEY=SENDGRID_API_KEY

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

EXPOSE 8080
ENTRYPOINT ["/app/hypatos_mail"]

